### ISSUE TITLE
ユーザーの登録（ログイン）／編集／ログアウト／退会機能（Twitter認証）

### ISSUE THREAD

**Issue by kassy916** [kassy916/Test#11]
## WHAT - 何を作るのか？
ユーザーがユーザー情報を登録／編集／退会できる機能
ユーザーがサイトにログイン／ログアウトできる機能

## WHY - 何故作るのか？
・スケジュール管理できるようにするため
お笑いライブに通っている人は、「行く」「行きたい」と思っているライブの情報をメモ帳やカレンダーアプリなどにコピーして個別に管理している人が多い。
「いいね」機能や「フォロー」機能で自動で自分のスケジュールを生成する機能があれば便利かと思われる。

## HOW - どうやって作るのか？
Twitter-oAuthによるログイン認証時に、下記の項目を取得してユーザー登録したい
・ユーザーID(nickname)
・名前(name)
・URL(url)
・プロフィール画像のURL（image_url)
・プロフィール内容(description)

## 参考URL
Twitter-omniauth Gemで使えるパラメータ
https://github.com/arunagw/omniauth-twitter

**Comment by kassy916** [comment]
Event.modelにカラムを追加したところ
  # Twitterログイン認証
  def self.find_for_oauth(auth, signed_in_resource=nil)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
       uid:      auth.uid,
       provider: auth.provider,
       nickname: auth[:info][:nickname],
       #name: auth[:info][:name],
       #image_url: auth[:info][:image],
       #description: auth[:info][:description]
       email:    User.dummy_email(auth),
       password: Devise.friendly_token[0, 20]
      )
    end
    user.skip_confirmation!
    # email仮をデータベースに保存するため、validationを一時的に無効化。
    user.save(validate: false)
    user
  end

# 参考URL
http://iccuu.hatenablog.com/entry/2014/12/29/172447

**Comment by sagaekeiga** [comment]
是非是非、マークダウン記法もお使いください。
https://qiita.com/tbpgr/items/989c6badefff69377da7

```ruby
def self.find_for_oauth(auth, signed_in_resource=nil)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    unless user
    user = User.create(
      uid: auth.uid,
      provider: auth.provider,
      nickname: auth[:info][:nickname],
      #name: auth[:info][:name],
      #image_url: auth[:info][:image],
      #description: auth[:info][:description]
      email: User.dummy_email(auth),
      password: Devise.friendly_token[0, 20]
    )
  end
  user.skip_confirmation!
  # email仮をデータベースに保存するため、validationを一時的に無効化。
  user.save(validate: false)
  user
end
```

ちなみに現場では、social認証系の情報は別テーブルを作成して管理してます。
テーブル多くなると開発大変になるかと思うので参考情報です！

`Users::Identity`
`models/users/identity.rb`

**Comment by kassy916** [comment]
うわーっぐぐってもDevise＋Twitter Omniauthのやりかたしかでてこなかったので、もしよければ別テーブル管理の方法についても参考サイトあれば教えていただきたいです・・・！

**Comment by sagaekeiga** [comment]
これとかですかね。
has_oneでUsers::Hogeみたいな形でいいと思うんですけど。
deviseは使ってOKです！
https://www.tech-tech.xyz/archives/5508606.html

**Comment by kassy916** [comment]
Twitterログインを別テーブルに切り出したかったのですが、やり方がわからず結局devise併用でUserテーブルに保存されています・・・

# app > controllers > users > omniauth_callback_controller.erb
```
  def twitter
    @user = User.find_for_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      if @user.sign_in_count == 0
        # 初回ログイン時のみ行いたい処理
        @geinins = GetTwitterFollowingList.new(@user.nickname,@user.id).execute
        # ここはエラーになる
        sign_in_and_redirect geinins_following_path
      end
      
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

    private

    def callback_from(provider)
      provider = provider.to_s

      @user = User.find_for_oauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)

        # request.env['omniauth.auth']に、OmniAuthによってHashのようにユーザーのデータが格納されている。
          session[:uid] = user.uid
        sign_in_and_redirect @user, event: :authentication
      else
        session["devise.#{provider}_data"] = request.env['omniauth.auth']
        redirect_to new_user_registration_url
      end
    end
end
```
