### ISSUE TITLE
ActionController::RoutingError (No route matches [GET] "/assets/bourbon"):

### ISSUE THREAD

**Issue by kassy916** [kassy916/Test#24]
### 前提・実現したいこと
作っているrailsプロジェクトをHerokuにデプロイしたい

### 発生している問題・エラーメッセージ
ActionController::RoutingError (No route matches [GET] "/assets/bourbon"):

開発環境ではエラーでもページを表示できるが、本番環境では不可

### 該当のソースコード
不明
application.html.erb読み込み時に起きているっぽいです

### 試したこと
app > assets > stylesheets配下にBourbonをインストールし、application.scssで
@import "bourbon";を追記すると当エラーは出なくなる。
ただし、別エラーで'Undefined variable: "$_buttons-list".'が発生しページを表示できなくなる。

いろいろネットの情報を参考にコピペしたりしていたので、どこが影響しているのか不明。
一旦CSS抜きでrubyの機能を開発したいので、BourbonインストールよりもHerokuのデプロイを優先したい。

#  参考サイト
https://rfs.jp/sb/css/sass/bourbon.html
https://www.tam-tam.co.jp/tipsnote/html_css/post8566.html

### 補足情報（FW/ツールのバージョンなど）
ここにより詳細な情報を記載してください。

**Comment by sagaekeiga** [comment]
bootstrapをおすすめしたいところです....!

**Comment by kassy916** [comment]
material datepickerの使用をやめてbourbonの使用を中止
