### ISSUE TITLE
raise OAuth::Unauthorized, response

### ISSUE THREAD

**Issue by kassy916** [kassy916/Test#27]
### 前提・実現したいこと
Twitterによるログイン認証(#11 も関連)

### 発生している問題・エラーメッセージ
raise OAuth::Unauthorized, response

### 該当のソースコード
app > controller > Application controller
app > controller > User controller
app > controller > devise > omniauth_callbacks_controller
app > model > User.model
config > secrets.yml
config > initializer > devise.rb
config > initializer > omniauth.rb
config > routes.rb
あたりが怪しい？

### 試したこと
ググって下記の原因を確認しましたが違いました。
1. アプリの設定画面のCallbackURLに何も入力されていない
2. API KEY（CONSUMER KEY）とAPI SECRET（CONSUMER SECRET）の設定が間違っている
3. コンピュータの時刻が狂っている（記事下部のコメントも参照してください）
4. アプリがTwitterからSuspendされてる

https://qiita.com/hirokishirai/items/5a43977a38ecd922bfb9

**Comment by sagaekeiga** [comment]
このコメントアウトは把握済みですか？
https://github.com/kassy916/Test/blob/72ee05be777d01e1b78829999f4153fc01fc9153/config/initializers/omniauth.rb#L2

**Comment by sagaekeiga** [comment]
これはもしやheroku上でのエラーでしょうか？

**Comment by sagaekeiga** [comment]
ソースコードのどこでエラーが出ているでしょうか？
おそらく404であれば認証ができてない（リクエスト情報に謝りがある）ので少なくともここは対象外になるかと。
https://github.com/kassy916/Test/blob/72ee05be777d01e1b78829999f4153fc01fc9153/app/models/user.rb#L25

気になるのは、deviseのomuniauth設定と独自のomuniauth設定が混在している箇所です...!
独自
https://github.com/kassy916/Test/blob/72ee05be777d01e1b78829999f4153fc01fc9153/config/initializers/omniauth.rb#L2

devise
https://github.com/kassy916/Test/blob/72ee05be777d01e1b78829999f4153fc01fc9153/app/models/user.rb#L4
https://github.com/kassy916/Test/blob/72ee05be777d01e1b78829999f4153fc01fc9153/config/initializers/devise.rb#L282

**Comment by sagaekeiga** [comment]
確認して欲しいissueにはhelp wanted ラベルをお願いします〜

**Comment by sagaekeiga** [comment]
こちら関係ありそうな。
https://twitter.com/gifu_w/status/1006765036289822720

**Comment by kassy916** [comment]
403のエラー
https://qiita.com/gifu_w/items/41d2c868317edea5045b

400 Bad request
・ブラウザのキャッシュを削除
・TwitterのAPI KeyとAPI Secretを環境変数に更新
https://qiita.com/pugiemonn/items/cc3a4068bace0eb3bf47
https://qiita.com/tkmkwgc/items/efc83d36d26a0eedfbd8

**Comment by kassy916** [comment]
# エラーメッセージ
undefined method `find_or_create_from_auth_hash' for #<Class:0x007f91069ba458>
Did you mean?  find_or_create_by

# 原因
ルーティングの設定が違いました
`get 'users/auth/:provider/callback', to: 'sessions#create'`
じゃなくて
`get 'auth/:provider/callback', to: 'sessions#create'`
でいいみたい
